/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AprendaRouteImport } from './routes/aprenda'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CriadoresRouteImport } from './routes/criadores'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as ContaCarteirasRouteImport } from './routes/conta.carteiras'
import { Route as ContaPerfilRouteImport } from './routes/conta.perfil'
import { Route as NftSlugRouteImport } from './routes/nft.$slug'
import { Route as PedidoOrderIdRouteImport } from './routes/pedido.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendaRoute = AprendaRouteImport.update({
  id: '/aprenda',
  path: '/aprenda',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CriadoresRoute = CriadoresRouteImport.update({
  id: '/criadores',
  path: '/criadores',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaCarteirasRoute = ContaCarteirasRouteImport.update({
  id: '/carteiras',
  path: '/carteiras',
  getParentRoute: () => ContaRoute,
} as any)
const ContaPerfilRoute = ContaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ContaRoute,
} as any)
const NftSlugRoute = NftSlugRouteImport.update({
  id: '/nft/$slug',
  path: '/nft/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoOrderIdRoute = PedidoOrderIdRouteImport.update({
  id: '/pedido/$orderId',
  path: '/pedido/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprenda': typeof AprendaRoute
  '/carrinho': typeof CarrinhoRoute
  '/conta': typeof ContaRouteWithChildren
  '/criadores': typeof CriadoresRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/mercado': typeof MercadoRoute
  '/pagamento': typeof PagamentoRoute
  '/conta/carteiras': typeof ContaCarteirasRoute
  '/conta/perfil': typeof ContaPerfilRoute
  '/nft/$slug': typeof NftSlugRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprenda': typeof AprendaRoute
  '/carrinho': typeof CarrinhoRoute
  '/conta': typeof ContaRouteWithChildren
  '/criadores': typeof CriadoresRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/mercado': typeof MercadoRoute
  '/pagamento': typeof PagamentoRoute
  '/conta/carteiras': typeof ContaCarteirasRoute
  '/conta/perfil': typeof ContaPerfilRoute
  '/nft/$slug': typeof NftSlugRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aprenda': typeof AprendaRoute
  '/carrinho': typeof CarrinhoRoute
  '/conta': typeof ContaRouteWithChildren
  '/criadores': typeof CriadoresRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/mercado': typeof MercadoRoute
  '/pagamento': typeof PagamentoRoute
  '/conta/carteiras': typeof ContaCarteirasRoute
  '/conta/perfil': typeof ContaPerfilRoute
  '/nft/$slug': typeof NftSlugRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprenda'
    | '/carrinho'
    | '/conta'
    | '/criadores'
    | '/criar-conta'
    | '/entrar'
    | '/mercado'
    | '/pagamento'
    | '/conta/carteiras'
    | '/conta/perfil'
    | '/nft/$slug'
    | '/pedido/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprenda'
    | '/carrinho'
    | '/conta'
    | '/criadores'
    | '/criar-conta'
    | '/entrar'
    | '/mercado'
    | '/pagamento'
    | '/conta/carteiras'
    | '/conta/perfil'
    | '/nft/$slug'
    | '/pedido/$orderId'
  id:
    | '__root__'
    | '/'
    | '/aprenda'
    | '/carrinho'
    | '/conta'
    | '/criadores'
    | '/criar-conta'
    | '/entrar'
    | '/mercado'
    | '/pagamento'
    | '/conta/carteiras'
    | '/conta/perfil'
    | '/nft/$slug'
    | '/pedido/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AprendaRoute: typeof AprendaRoute
  CarrinhoRoute: typeof CarrinhoRoute
  ContaRoute: typeof ContaRouteWithChildren
  CriadoresRoute: typeof CriadoresRoute
  CriarContaRoute: typeof CriarContaRoute
  EntrarRoute: typeof EntrarRoute
  MercadoRoute: typeof MercadoRoute
  PagamentoRoute: typeof PagamentoRoute
  NftSlugRoute: typeof NftSlugRoute
  PedidoOrderIdRoute: typeof PedidoOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprenda': {
      id: '/aprenda'
      path: '/aprenda'
      fullPath: '/aprenda'
      preLoaderRoute: typeof AprendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criadores': {
      id: '/criadores'
      path: '/criadores'
      fullPath: '/criadores'
      preLoaderRoute: typeof CriadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/carteiras': {
      id: '/conta/carteiras'
      path: '/carteiras'
      fullPath: '/conta/carteiras'
      preLoaderRoute: typeof ContaCarteirasRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/perfil': {
      id: '/conta/perfil'
      path: '/perfil'
      fullPath: '/conta/perfil'
      preLoaderRoute: typeof ContaPerfilRouteImport
      parentRoute: typeof ContaRoute
    }
    '/nft/$slug': {
      id: '/nft/$slug'
      path: '/nft/$slug'
      fullPath: '/nft/$slug'
      preLoaderRoute: typeof NftSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$orderId': {
      id: '/pedido/$orderId'
      path: '/pedido/$orderId'
      fullPath: '/pedido/$orderId'
      preLoaderRoute: typeof PedidoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ContaRouteChildren {
  ContaCarteirasRoute: typeof ContaCarteirasRoute
  ContaPerfilRoute: typeof ContaPerfilRoute
}

const ContaRouteChildren: ContaRouteChildren = {
  ContaCarteirasRoute: ContaCarteirasRoute,
  ContaPerfilRoute: ContaPerfilRoute,
}

const ContaRouteWithChildren = ContaRoute._addFileChildren(ContaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AprendaRoute: AprendaRoute,
  CarrinhoRoute: CarrinhoRoute,
  ContaRoute: ContaRouteWithChildren,
  CriadoresRoute: CriadoresRoute,
  CriarContaRoute: CriarContaRoute,
  EntrarRoute: EntrarRoute,
  MercadoRoute: MercadoRoute,
  PagamentoRoute: PagamentoRoute,
  NftSlugRoute: NftSlugRoute,
  PedidoOrderIdRoute: PedidoOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
